version: '2.2'

volumes:
  mysql_data: {}
  es_data_1: {}
  es_data_2: {}
  es_data_3: {}
  es_data_4: {}
  es_data_5: {}
  influxdb_data: {}
  grafana_data: {}

networks:
  master_project:

services:

  mysql:
    image: mysql:5.7
    volumes:
    - mysql_data:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=root
    expose:
    - "3306"
    networks:
    - master_project

  es_head:
    image: mobz/elasticsearch-head:5
    ports:
    - 9100:9100
    depends_on:
    - es_master_1
    networks:
    - master_project

  es_proxy:
    image: nginx:1.13.7
    volumes:
    - /hosthome/truppert/projects/master-project/example-system/nginx-es:/etc/nginx
    ports:
    - "9200:9200"
    expose:
    - "9200"
    depends_on:
    - es_master_1
    - es_master_2
    - es_master_3
    - es_data_1
    - es_data_2
    - es_data_3
    - es_data_4
    - es_data_5
    networks:
    - master_project

  es_master_1:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1
    container_name: es_master_1
    environment:
    - cluster.name=webapp-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - "discovery.zen.ping.unicast.hosts=es_master_2"
    - "discovery.zen.minimum_master_nodes=2"
    - "node.master=true"
    - "node.data=false"
    - "node.name=es_master_1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
    - master_project

  es_master_2:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1
    container_name: es_master_2
    environment:
    - cluster.name=webapp-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - "discovery.zen.ping.unicast.hosts=es_master_1"
    - "discovery.zen.minimum_master_nodes=2"
    - "node.master=true"
    - "node.data=false"
    - "node.name=es_master_2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
    - es_master_1
    networks:
    - master_project

  es_master_3:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1
    container_name: es_master_3
    environment:
    - cluster.name=webapp-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - "discovery.zen.ping.unicast.hosts=es_master_1,es_master_2"
    - "discovery.zen.minimum_master_nodes=2"
    - "node.master=true"
    - "node.data=false"
    - "node.name=es_master_3"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
    - es_master_2
    networks:
    - master_project

  es_data_1:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1
    container_name: es_data_1
    volumes:
    - es_data_1:/usr/share/elasticsearch/data
    environment:
    - cluster.name=webapp-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - "discovery.zen.ping.unicast.hosts=es_master_1,es_master_2,es_master_3"
    - "node.master=false"
    - "node.data=true"
    - "node.name=es_data_1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
    - es_master_3
    networks:
    - master_project

  es_data_2:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1
    container_name: es_data_2
    volumes:
    - es_data_2:/usr/share/elasticsearch/data
    environment:
    - cluster.name=webapp-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - "discovery.zen.ping.unicast.hosts=es_master_1,es_master_2,es_master_3"
    - "node.master=false"
    - "node.data=true"
    - "node.name=es_data_2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
    - es_master_3
    networks:
    - master_project

  es_data_3:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1
    container_name: es_data_3
    volumes:
    - es_data_3:/usr/share/elasticsearch/data
    environment:
    - cluster.name=webapp-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - "discovery.zen.ping.unicast.hosts=es_master_1,es_master_2,es_master_3"
    - "node.master=false"
    - "node.data=true"
    - "node.name=es_data_3"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
    - es_master_3
    networks:
    - master_project

  es_data_4:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1
    container_name: es_data_4
    volumes:
    - es_data_4:/usr/share/elasticsearch/data
    environment:
    - cluster.name=webapp-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - "discovery.zen.ping.unicast.hosts=es_master_1,es_master_2,es_master_3"
    - "node.master=false"
    - "node.data=true"
    - "node.name=es_data_4"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
    - es_master_3
    networks:
    - master_project

  es_data_5:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1
    container_name: es_data_5
    volumes:
    - es_data_5:/usr/share/elasticsearch/data
    environment:
    - cluster.name=webapp-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - "discovery.zen.ping.unicast.hosts=es_master_1,es_master_2,es_master_3"
    - "node.master=false"
    - "node.data=true"
    - "node.name=es_data_5"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
    - es_master_3
    networks:
    - master_project

  web_app:
    build: ./example-system/web-app
    volumes:
    - /hosthome/truppert/projects/master-project/example-system/web-app:/app/web-app
    depends_on:
    - mysql
    - es_proxy
    - influxdb
    command: "rails server --pid /tmp/server.pid"
    scale: 5
    networks:
    - master_project

  proxy:
    image: nginx:1.13.7
    volumes:
    - /hosthome/truppert/projects/master-project/example-system/nginx:/etc/nginx
    ports:
    - "80:80"
    depends_on:
    - web_app
    networks:
    - master_project

  influxdb:
    image: influxdb:1.4
    expose:
    - "8086"
    ports:
    - 8086:8086
    environment:
    - INFLUXDB_DB=telegraf
    volumes:
    - influxdb_data:/var/lib/influxdb
    networks:
    - master_project

  grafana:
    image: grafana/grafana
    ports:
    - 3005:3000
    volumes:
    - grafana_data:/var/lib/grafana
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=foobar
    - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
    - influxdb
    networks:
    - master_project

  telegraf:
    image: telegraf:1.5
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:ro
    - /sys:/sys:ro
    - /var/lib/docker:/var/lib/docker:ro
    - /hosthome/truppert/projects/master-project/monitoring/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
    - influxdb
    - mysql
    - proxy
    - es_proxy
    - es_master_1
    - es_master_2
    - es_master_3
    - es_data_1
    - es_data_2
    - es_data_3
    - es_data_4
    - es_data_5
    networks:
    - master_project

  gremlins:
    image: truppert/gremlins
    environment:
    - ENTROPY_PROBABILITY=.9
    - ENTROPY_FREQUENCY=1
    - ENTROPY_FAILURES=latency
    privileged: true
    volumes:
    - /hosthome/truppert/projects/gremlins:/app
    network_mode: "host"
    command: "sleep 10000"

  ts_list:
    build: ./traffic-simulator
    volumes:
    - /hosthome/truppert/projects/master-project/traffic-simulator:/app/traffic-simulator
    depends_on:
    - proxy
    - influxdb
    networks:
    - master_project
    command: "ruby traffic-simulator.rb /articles 1"

  ts_search:
    build: ./traffic-simulator
    volumes:
    - /hosthome/truppert/projects/master-project/traffic-simulator:/app/traffic-simulator
    depends_on:
    - proxy
    - influxdb
    networks:
    - master_project
    command: "ruby traffic-simulator.rb /articles/search/russia 1"
