version: '2'

services:

  mysql:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=dHlsZXJ3YXNoZXJlCg
    expose:
    - "3306"
    ports:
    - 3307:3306

  web_app:
    build: ./web-app
    volumes:
    - ./web-app:/app/web-app
    # ports:
    # - 3000:3000
    links:
    - "mysql:mysql"
    command: "rails server --pid /tmp/server.pid"

  proxy:
    image: nginx:1.13.7
    volumes:
    - ./nginx:/etc/nginx
    ports:
    - "80:80"
    links:
    - web_app
