version: '2.2'

volumes:
  influxdb_data: {}
  grafana_data: {}

services:

  influxdb:
    image: influxdb:1.4
    expose:
    - "8086"
    ports:
    - 8086:8086
    environment:
    - INFLUXDB_DB=telegraf
    volumes:
    - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    ports:
    - 3005:3000
    volumes:
    - grafana_data:/var/lib/grafana
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=foobar
    - GF_USERS_ALLOW_SIGN_UP=false
    links:
    - influxdb:influxdb
    depends_on:
    - influxdb

