version: '2.2'

volumes:
  mysql_data: {}

services:

  mysql:
    image: mysql:5.7
    volumes:
    - mysql_data:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=root
    expose:
    - "3306"
    ports:
    - 3307:3306
